#!/bin/bash
total 12
-rw-r--r-- 1 root root 54 Mar 30 11:10 0-current_working_directory
-rw-r--r-- 1 root root 37 Mar 30 11:11 1-listit
-rw-r--r-- 1 root root  5 Mar 30 11:15 2-bring_me_home
-rw-r--r-- 1 root root  0 Mar 30 11:16 3-listfiles
