#!/bin/bash
total 16
drwxr-xr-x 2 root root 122 Mar 30 11:17 .
drwxr-xr-x 4 root root  43 Mar 30 11:10 ..
-rw-r--r-- 1 root root  54 Mar 30 11:10 0-current_working_directory
-rw-r--r-- 1 root root  37 Mar 30 11:11 1-listit
-rw-r--r-- 1 root root   5 Mar 30 11:15 2-bring_me_home
-rw-r--r-- 1 root root 230 Mar 30 11:16 3-listfiles
-rw-r--r-- 1 root root   0 Mar 30 11:17 4-listmorefiles
